services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  SimpleFormsBundle\Form\SimpleForm: ~
  SimpleFormsBundle\CalculatedValue\FieldSlugCalculator: ~
  SimpleFormsBundle\Service\SimpleFormService: ~
  # Installer
  SimpleFormsBundle\Tools\Installer:
    public: true
    arguments:
      $bundle: "@=service('kernel').getBundle('SimpleFormsBundle')"