name: "Codeception Tests Pimcore 6.9"

on: push

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
    PIMCORE_ENVIRONMENT: test
    PIMCORE_TEST: 1
    PIMCORE_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/pimcore_test"

jobs:
    codeception-tests:
        name: "Codeception tests"
        runs-on: "ubuntu-20.04"
        continue-on-error: false
        strategy:
            matrix:
                include:
                    - { php-version: 7.4, database: "mariadb:10.5" }

        services:
            mariadb:
                image: "${{ matrix.database }}"
                ports:
                    - 33006:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  extensions: imagick
                  ini-values: display_errors=On, display_startup_errors=On, error_reporting=32767
                  php-version: "${{ matrix.php-version }}"

            - name: Verify MariaDB connection
              run: |
                  cp .github/ci/files-pimcore-69/.my.cnf ~/.my.cnf
                  while ! mysqladmin ping --silent; do
                    sleep 1
                  done
            - name: "Setup Pimcore environment"
              run: |
                  mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"
                  .github/ci/setup-pimcore-69.sh
            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: highest

            - name: "Test environment infos"
              run: |
                  mysql -e "SELECT VERSION();"
                  php -i
                  ./bin/console pimcore:system:requirements:check
            - name: "Run Codeception"
              run: "vendor/bin/codecept run -c . -vvv --json"
